name = "ozbloom"
main = "src/worker.ts"
compatibility_date = "2026-06-14"
account_id = "3bea2e6d6f93b5cc822b36b69958d4cd"

routes = [
  { pattern = "ozbloom.mihassan.com", custom_domain = true },
]

[[d1_databases]]
binding = "DB"
database_name = "ozbloom-db"
database_id = "273c4c7e-c370-44ad-adb1-618715cec239"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "ozbloom-images"

[assets]
directory = "./dist"
not_found_handling = "single-page-application"
run_worker_first = ["/api/*"]
